name: Build & Push Frontend

on:
  push:
    paths:
      - "frontend/**"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/tasktracker-frontend:latest ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/tasktracker-frontend:latest
